name: Android CI

on:
  push:
    tags:
      - '*'          # билд/релиз по тегам
  workflow_dispatch:       # запуск вручную

env:
  ANDROID_COMPILE_SDK: '35'
  ANDROID_BUILD_TOOLS: '35.0.0'
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # передаём в Gradle секреты для подписи
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'   # кэш ~/.gradle

      - uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-${ANDROID_COMPILE_SDK}" \
                     "build-tools;${ANDROID_BUILD_TOOLS}"
          yes | sdkmanager --licenses

      - name:  Restore keystore from secret
        run: |
          echo "$SENDSAY_JKS_B64" | base64 -d > app/Sendsay.jks
        env:
          $SENDSAY_JKS_B64: ${{ secrets.$SENDSAY_JKS_B64 }}

      - name:  Restore google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON_B64" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON_B64: ${{ secrets.GOOGLE_SERVICES_JSON_B64 }}

      - name:  Restore agconnect-services.json
        run: |
          echo "$AGCONNECT_SERVICES_JSON_B64" | base64 -d > app/agconnect-services.json
        env:
          AGCONNECT_SERVICES_JSON_B64: ${{ secrets.AGCONNECT_SERVICES_JSON_B64 }}

      - name: Assemble release
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/*/release/*.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apk
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
